CREATE DATABASE COMIDA_RAPIDA;

USE COMIDA_RAPIDA;

CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255)
);

CREATE TABLE PLATILLO (
    ID_PLATILLO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_PLATILLO VARCHAR(255),
    PRECIO FLOAT,
    DESCRIPCION VARCHAR(255),
    ID_CATEGORIA INT,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE CLIENTE (
    DUI VARCHAR(10) PRIMARY KEY,
    NOMBRE VARCHAR(255),
    APELLIDO VARCHAR(255),
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(10)
);

CREATE TABLE MESA (
    ID_MESA INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO_MESA VARCHAR(50)
);

CREATE TABLE USUARIO (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    CONTRASEÑA VARCHAR(255),
    ROL VARCHAR(50),
    USUARIO VARCHAR(255),
    NOMBRE_EMPLEADO VARCHAR(255),
    TELEFONO VARCHAR(10)
);

CREATE TABLE PEDIDO (
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    FECHA VARCHAR(50),
    DUI_CLIENTE VARCHAR(10),
    ID_MESA INT,
    ESTADO VARCHAR(50),
    TOTAL FLOAT,
    PAGO VARCHAR(50),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (DUI_CLIENTE) REFERENCES CLIENTE(DUI),
    FOREIGN KEY (ID_MESA) REFERENCES MESA(ID_MESA)
);

CREATE TABLE DETALLE_PEDIDO (
    ID_DETALLE_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PLATILLO INT,
    ID_PEDIDO INT,
    CANTIDAD INT,
    SUBTOTAL FLOAT,
    FOREIGN KEY (ID_PLATILLO) REFERENCES PLATILLO(ID_PLATILLO),
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO)
);
