-- Crear tabla CATEGORIA
CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT PRIMARY KEY,
    NOMBRE VARCHAR(50)
);

-- Crear tabla PLATILLO
CREATE TABLE PLATILLO (
    ID_PLATILLO INT PRIMARY KEY,
    NOMBRE_PLATILLO VARCHAR(50),
    PRECIO FLOAT,
    DESCRIPCION VARCHAR(255),
    ID_CATEGORIA INT,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

-- Crear tabla CLIENTE
CREATE TABLE CLIENTE (
    DUI VARCHAR(10) PRIMARY KEY,
    NOMBRE VARCHAR(70),
    APELLIDO VARCHAR(70),
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(8)
);

-- Crear tabla MESA
CREATE TABLE MESA (
    ID_MESA INT PRIMARY KEY,
    NUMERO_MESA VARCHAR(4)
);

-- Crear tabla USUARIO
CREATE TABLE USUARIO (
    ID_USUARIO INT PRIMARY KEY,
    CONTRASEÑA VARCHAR(10),
    ROL VARCHAR(1),
    USUARIO VARCHAR(15),
    NOMBRE_EMPLEADO VARCHAR(70),
    TELEFONO VARCHAR(8)
);

-- Crear tabla PEDIDO
CREATE TABLE PEDIDO (
    ID_PEDIDO INT PRIMARY KEY,
    ID_USUARIO INT,
    FECHA DATETIME,
    DUI_CLIENTE VARCHAR(9),
    ID_MESA INT,
    ESTADO VARCHAR(1),
    TOTAL FLOAT,
    PAGO VARCHAR(40),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (DUI_CLIENTE) REFERENCES CLIENTE(DUI),
    FOREIGN KEY (ID_MESA) REFERENCES MESA(ID_MESA)
);

-- Crear tabla DETALLE_PEDIDO
CREATE TABLE DETALLE_PEDIDO (
    ID_DETALLE_PEDIDO INT PRIMARY KEY,
    ID_PLATILLO INT,
    ID_PEDIDO INT,
    CANTIDAD INT,
    SUBTOTAL FLOAT,
    FOREIGN KEY (ID_PLATILLO) REFERENCES PLATILLO(ID_PLATILLO),
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO)
);
